Changing root builddev script to take an optional 5th parameter that provides the root filesystem to put on the target before copying any artifacts from the build process.

diff --git a/builddev b/builddev
--- a/builddev
+++ b/builddev
@@ -6,12 +6,18 @@ platform="${1}"
 hostname="${2}"
 targetDevice="${3}"
 blockFilesystem="${4}"
+rootFilesystemSource="${5}"
 filesystem="fat32"
 blocksPerOverlay=8
 
 if [ "${platform}" = "" ] || [ "${hostname}" = "" ] \
 		|| [ "${targetDevice}" = "" ] || [ "${blockFilesystem}" = "" ]; then
-	echo "Usage: ${0} <ArduinoSamd21|AgonLight2> <hostname> <target device> <blockFilesystem>" >&2
+	echo "Usage: ${0} <ArduinoSamd21|AgonLight2> <hostname> <target device> <blockFilesystem> [rootFilesystemSource]" >&2
+	exit 1
+fi
+
+if [ -n "${rootFilesystemSource}" ] && [ ! -d "${rootFilesystemSource}" ]; then
+	echo "ERROR: No root filesystem source directory found at ${rootFilesystemSource}." >&2
 	exit 1
 fi
 
@@ -107,6 +113,11 @@ trap "rm -rf \"${mountDir}\"" ERR EXIT
 echo '2048,,0c' | sudo sfdisk "${targetDevice}"
 sudo mkfs.vfat -F 32 "${targetDevice}p1" -n NanoOs
 sudo mount "${targetDevice}p1" "${mountDir}"
+
+if [ -n "${rootFilesystemSource}" ]; then
+	sudo cp -r "${rootFilesystemSource}/." "${mountDir}"
+fi
+
 sudo mkdir -p "${mountDir}/usr"
 sudo cp -r usr/bin "${mountDir}/usr"
 sudo cp -r usr/lib "${mountDir}/usr"
